lista = ["Maçã", "Cachorro", "Futebol", "Arco-íris", "Viagem",
         "Livro", "Café", "Música", "Piano", "Cinema",
         "Computador", "Natureza", "Dança", "Gatos", "Fotografia",
         "Chocolate", "Amizade", "Praia", "Astronomia", "Pizza",
         "Montanha", "Desenho", "Moda", "Corrida", "Crianças",
         "Jardinagem", "Artesanato", "Vinho", "Espiritualidade", "Aventura",
         "Poesia", "Escrita", "Cachoeira", "Quebra-cabeça", "Bicicleta",
         "Meditação", "História", "Comédia", "Pintura", "Guitarra",
         "Esportes", "Teatro", "Espaço", "Educação", "Negócios",
         "Sushi", "Churrasco", "Documentários", "Praças", "Trilhas",
         "Amor", "Fotografia de animais", "Bebidas exóticas", "Confeitaria", "Carros",
         "Parques temáticos", "Arquitetura", "Política", "Escultura", "Sorvete",
         "Cachecol", "Gelato", "Viagens de trem", "Desafios", "Vida selvagem",
         "Escalada", "Surfe", "Comédia romântica", "Desfiles de moda", "Origami",
         "Gastronomia molecular", "Relógios antigos", "Comida de rua", "Aquarela", "Motocicletas",
         "Escotismo", "Cafeterias aconchegantes", "Corrida de cavalos", "Histórias em quadrinhos", "Mergulho",
         "Parques nacionais", "Cruzeiros", "História da arte", "Tatuagens", "RPG de mesa",
         "Drones", "Jardinagem vertical", "Comédia stand-up", "Filmes de ação", "Café da manhã",
         "Velejar", "Moda retrô", "Yoga", "Palhaços", "Chá"
         ]